import type { Metadata } from "next";
import Navbar from "./components/navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Arham Memorial Coaching",
  description: "Generated by Arham Memorial Coaching",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="sticky top-0 z-[9999]">
          <Navbar />
        </div>
        <main>{children}</main>
      </body>
    </html>
  );
}
